export const THEMES = [
  { value: "vs-light", label: "VS Light" },
  { value: "vs-dark", label: "VS Dark" },
  { value: "Active4D", label: "Active4D" },
  { value: "AllHallowsEve", label: "All Hallows Eve" },
  { value: "Amy", label: "Amy" },
  { value: "BirdsOfParadise", label: "Birds of Paradise" },
  { value: "Blackboard", label: "Blackboard" },
  { value: "BrillianceBlack", label: "Brilliance Black" },
  { value: "BrillianceDull", label: "Brilliance Dull" },
  { value: "ChromeDevTools", label: "Chrome DevTools" },
  { value: "CloudsMidnight", label: "Clouds Midnight" },
  { value: "Clouds", label: "Clouds" },
  { value: "Cobalt", label: "Cobalt" },
  { value: "Cobalt2", label: "Cobalt2" },
  { value: "Dawn", label: "Dawn" },
  { value: "DominionDay", label: "Dominion Day" },
  { value: "Dracula", label: "Dracula" },
  { value: "Dreamweaver", label: "Dreamweaver" },
  { value: "Eiffel", label: "Eiffel" },
  { value: "EspressoLibre", label: "Espresso Libre" },
  { value: "GitHubDark", label: "GitHub Dark" },
  { value: "GitHubLight", label: "GitHub Light" },
  { value: "GitHub", label: "GitHub" },
  { value: "IDLE", label: "IDLE" },
  { value: "idleFingers", label: "idleFingers" },
  { value: "iPlastic", label: "iPlastic" },
  { value: "Katzenmilch", label: "Katzenmilch" },
  { value: "krTheme", label: "krTheme" },
  { value: "KuroirTheme", label: "Kuroir Theme" },
  { value: "LAZY", label: "LAZY" },
  { value: "MagicWBAmiga", label: "MagicWB (Amiga)" },
  { value: "MerbivoreSoft", label: "Merbivore Soft" },
  { value: "Merbivore", label: "Merbivore" },
  { value: "monoindustrial", label: "monoindustrial" },
  { value: "MonokaiBright", label: "Monokai Bright" },
  { value: "Monokai", label: "Monokai" },
  { value: "NightOwl", label: "Night Owl" },
  { value: "Nord", label: "Nord" },
  { value: "OceanicNext", label: "Oceanic Next" },
  { value: "PastelsOnDark", label: "Pastels on Dark" },
  { value: "SlushAndPoppies", label: "Slush and Poppies" },
  { value: "SolarizedDark", label: "Solarized-dark" },
  { value: "SolarizedLight", label: "Solarized-light" },
  { value: "SpaceCadet", label: "SpaceCadet" },
  { value: "Sunburst", label: "Sunburst" },
  { value: "TextmateMacClassic", label: "Textmate (Mac Classic)" },
  { value: "themelist", label: "themelist" },
  { value: "TomorrowNightBlue", label: "Tomorrow-Night-Blue" },
  { value: "TomorrowNightBright", label: "Tomorrow-Night-Bright" },
  { value: "TomorrowNightEighties", label: "Tomorrow-Night-Eighties" },
  { value: "TomorrowNight", label: "Tomorrow-Night" },
  { value: "Tomorrow", label: "Tomorrow" },
  { value: "Twilight", label: "Twilight" },
  { value: "UpstreamSunburst", label: "Upstream Sunburst" },
  { value: "VibrantInk", label: "Vibrant Ink" },
  { value: "XcodeDefault", label: "Xcode Default" },
  { value: "Zenburnesque", label: "Zenburnesque" },
];
